<?php

namespace Tests\Feature\Services;

use App\Events\Campaign\CampaignCompleted;
use App\Events\Campaign\CampaignConfirmed;
use App\Events\Campaign\CampaignImportingPaused;
use App\Events\Campaign\CampaignSchedulingCompleted;
use App\Events\Campaign\CampaignSchedulingStarted;
use App\Events\Campaign\CampaignUploaded;
use App\Models\Lead\Lead;
use App\Models\Campaign\Campaign;
use App\Models\Campaign\CampaignStatus;
use App\Services\DataTransferObjects\LeadData;
use App\Services\DataTransferObjects\CampaignData;
use App\Services\CampaignService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CampaignServiceTest extends TestCase
{
    use RefreshDatabase;

    protected CampaignService $service;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new CampaignService();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_a_lead_list_can_be_uploaded_and_leads_created()
    {
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();

        $leadsToCreate = $data->leads->count();

        $this->expectsEvents(CampaignUploaded::class);
        $leadList = $this->service->create($data);
        $this->assertInstanceOf(Campaign::class, $leadList);
        $this->assertEquals($leadsToCreate, $leadList->leads()->count());
        $this->assertDatabaseHas('leads', [
            'campaign_id' => $leadList->id,
            'client_id' => $leadList->client_id
        ]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_a_lead_list_can_be_confirmed_and_its_leads_scheduled()
    {
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();

        $leadList = $this->service->create($data);

        $this->expectsEvents(CampaignConfirmed::class);
        $this->expectsEvents(CampaignSchedulingStarted::class);
        $this->expectsEvents(CampaignSchedulingCompleted::class);
        $leadList = $this->service->confirm($leadList);
        $this->assertDatabaseHas('campaigns', [
            'id' => $leadList->id,
            'campaign_status_id' => CampaignStatus::CONFIRMED,
        ]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_importing_of_a_lead_list_can_be_paused()
    {
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();
        $leadsToBeCreatedCount = $data->leads->count();

        $leadList = $this->service->create($data);
        $this->service->confirm($leadList);

        $this->expectsEvents(CampaignImportingPaused::class);
        $leadList = $this->service->pauseImporting($leadList);
        $this->assertDatabaseHas('campaigns', [
            'id' => $leadList->id,
            'campaign_status_id' => CampaignStatus::PAUSED,
        ]);

        $leadsNotImportedCount = $leadList->leadsNotImported()->count();
        $this->assertEquals($leadsToBeCreatedCount, $leadsNotImportedCount);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_importing_of_a_lead_list_can_be_resumed()
    {
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();

        $leadList = $this->service->create($data);
        $this->service->confirm($leadList);
        $leadList = $this->service->pauseImporting($leadList);

        $this->expectsEvents(CampaignSchedulingStarted::class);
        $this->expectsEvents(CampaignSchedulingCompleted::class);
        $leadList = $this->service->resumeImporting($leadList);
        $this->assertDatabaseHas('campaigns', [
            'id' => $leadList->id,
            'campaign_status_id' => CampaignStatus::IMPORT_STARTED,
        ]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_a_lead_list_can_be_terminated_and_its_leads_closed()
    {
        $this->assertTrue(true);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_a_lead_list_can_be_marked_completed()
    {
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();

        $leadList = $this->service->create($data);
        $this->expectsEvents(CampaignCompleted::class);
        $leadList = $this->service->complete($leadList);
        $this->assertEquals($leadList->campaign_status_id, CampaignStatus::COMPLETED);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_a_lead_list_scheduled_in_the_past_will_be_scheduled_for_import_starting_today()
    {
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();
        $data->start_work_at = now()->subDay();

        $leadList = $this->service->create($data);

        // If it's less than right now, use right now
        $date = $this->service->getFirstDayAvailableForSchedulingWork($leadList);
        // The before carbon instance is less than the scheduled start date
        $this->assertTrue($date->isToday());
        $this->assertTrue($date->isStartOfDay());
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_a_lead_list_scheduled_for_work_in_the_future_is_scheduled_correctly() {
        // Test the scheduling of starting work in the future
        /** @var CampaignData $data */
        $data = CampaignData::factory()->make();
        $data->start_work_at = now()->addDay();

        $leadList = $this->service->create($data);

        $date = $this->service->getFirstDayAvailableForSchedulingWork($leadList);
        // The date is tomorrow
        $this->assertTrue($date->isTomorrow());
        $this->assertTrue($date->isStartOfDay());

    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_that_lead_list_leads_will_be_scheduled_according_to_lead_list_parameters()
    {

        /** @var CampaignData $data */
        $data = CampaignData::factory()->make([
            'label' => 'Test of scheduling',
            // Create the lead list with 10 leads, and that the start work date is today
            'leads' => LeadData::factory()->count(10)->make(),
            'start_work_at' => now(),
            // schedule the lead list with 5 leads per day.
            'max_leads_to_import_per_day' => 5,
        ]);

        $leadList = $this->service->create($data);

        $totalLeadsOnLeadList = $leadList->leads()->count();
        $this->assertEquals($totalLeadsOnLeadList, 10);
        $leadsAwaitingSchedulingOnList = $leadList->leadsAwaitingScheduling()->count();
        $this->assertTrue($leadsAwaitingSchedulingOnList === 10);

        $this->service->scheduleLeads($leadList);

        $countOfLeadsReadyForImport = Lead::query()->readyForImport()->count();
        $this->assertEquals($countOfLeadsReadyForImport, 5, 'Lead list leads to be scheduled for today is incorrect');

        $toBeImportedTomorrow = Lead::query()->readyForImportOnDay(now()->addDay()->startOfDay())->count();
        $this->assertEquals($toBeImportedTomorrow, 5, 'Lead list leads to be scheduled for tomorrow is incorrect');

        // Confirm that all the leads have a lead status of AWAITING_IMPORT
        // Confirm that the leads are are scheduled 5 for today, and 5 for tomorrow
        // Confirm that the leads are scheduled for the start of the day
    }
}
