<?php

namespace Tests\Feature\Services;

use App\Contracts\Lead\CreatesNewLeadContract;
use App\Events\Lead\LeadReceived;
use App\Http\DataTransferObjects\LeadData;
use App\Http\Services\LeadService;
use App\Jobs\Lead\ImportLeadJob;
use App\Models\Client\Client;
use App\Models\Lead\Lead;
use App\Models\Lead\LeadProvider;
use App\Models\Lead\LeadStatus;
use App\Models\Lead\LeadType;
use Carbon\Carbon;
use Database\Factories\Lead\LeadDataFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\Mocks\Lead\CreateNewLeadMock;
use Tests\TestCase;

class LeadServiceTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    protected LeadService $service;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        //$this->app->bind(CreatesNewLeadContract::class, CreateNewLeadMock::class);

        $this->service = new LeadService();
    }

    /**
     *
     */
    public function test_that_when_a_provider_sends_us_lead_data_we_will_create_a_new_lead() {
        /** @var LeadData $dto */
        $dto = LeadData::factory()->make([]);

        $this->expectsEvents(LeadReceived::class);
        $lead = $this->service->receiveLeadFromProvider($dto);
        $this->assertInstanceOf(Lead::class, $lead);

        $this->assertDatabaseHas('leads', [
            'client_id' => $dto->client_id,
            'lead_type_id' => $dto->lead_type_id,
            'lead_status_id' => LeadStatus::AWAITING_IMPORT,
            'first_name' => $dto->first_name,
            'last_name' => $dto->last_name,
            'full_name' => $dto->full_name
        ]);
    }
}
