<?php

namespace Tests\Feature\Services;

use App\Models\Lead\Lead;
use App\Models\Sequence\Sequence;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Services\LeadSequenceService;
use Tests\TestCase;

class LeadSequenceServiceTest extends TestCase
{
    use RefreshDatabase;

    protected LeadSequenceService $service;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = app(LeadSequenceService::class);
    }

    /*****************************************************************************
     * Lead Sequence Assignment
     ****************************************************************************/

    public function test_assigning_a_sequence() {
        $sequence = Sequence::factory()->create();
        $lead = Lead::factory()->create();

        $this->service->assignSequence($sequence, $lead);
        $this->assertDatabaseHas('lead_sequence', [
            'lead_id' => $lead->id,
            'sequence_id' => $sequence->id,
            'closed_at' => null,
        ]);
    }

    public function test_creating_a_sequence_task() {
        /** @var Sequence $sequence */
        $sequence = Sequence::factory()->create();

        /** @var Lead $lead */
        $lead = Lead::factory()->create();

        $this->service->assignSequence($sequence, $lead);

        $task = $this->service->createNextTask($lead);
    }

    /*****************************************************************************
     * Lead Sequence Task Creation
     ****************************************************************************/
    public function test_assigning_a_sequence_and_creating_first_task() {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    public function test_missing_sequence_scenario_when_creating_new_task_for_lead()
    {
        $this->assertTrue(true);
    }

    public function test_scenario_where_there_are_no_remaining_sequence_actions_for_sequence_assigned_to_lead()
    {
        $this->assertTrue(true);
    }

    /*****************************************************************************
     * Lead Sequence Ending
     ****************************************************************************/

    public function test_ending_a_sequence() {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
